name: Github actions poetry test
on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: actions-setup-cmake
              uses: jwlawson/actions-setup-cmake@v1.14.0

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.9'

            - name: Setup Poetry
              uses: abatilo/actions-poetry@v2.1.6
            
            - name: Setup Project
              run: make setup-project
            






